### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by katat** [ququzone/ckb-udt-cli#1]
Hi @ququzone 

I am trying to build the cli following the instruction in the readme and play around with the sUDT issuance. The commands I executed successfully is:
```
export GOPROXY=https://goproxy.io
go mod download
```

But when I try to execute `go build .`, it throws the following error:
```
cannot find module for path net
```

I am pretty new to `go` dev environment, not quite sure what went wrong with the command. I guess it could be due to my go dev environment. Appreciated if you can spot the cause and let me know how to fix this.

**Comment by ququzone** [comment]
I guess this error cause by go version or GOPATH.

If you just need to run `ckb-udt-cli`, you can install it with the following command:
```
go get github.com/ququzone/ckb-udt-cli
```
Then you can use `ckb-udt-cli` directly. Binary can be found in `$GOPATH/bin`.

If you want change code locally, you should move code from $GOPATH.

**Comment by katat** [comment]
Thanks @ququzone for the suggestions.

I just tried to upgrade my go version from 1.11 to 1.14 on mac, and now the build works.

Cheers
